### ISSUE TITLE
Connection failed to DB

### ISSUE THREAD

**Issue by clem9669** [lebalz/sql-injection-demo#1]
Hey 👋 

Thanks for this good repo !

I have an issue, I cannot connect with the DB, even if I kept the same credentials as you did in the README.

![2022-01-03_18h00_25](https://user-images.githubusercontent.com/18504086/147958388-fb8484fb-1f43-41cb-a183-af5551ed984d.png)

I have add the mariadb user and granted the priv: 
(excuse the synthax, it is from .mysql_history)

![2022-01-03_18h04_18](https://user-images.githubusercontent.com/18504086/147958744-68aafdee-94d8-47b2-a4d1-5a5de3932ccf.png)

Do you know where my mistake could come from ?

Thanks 😃

**Comment by clem9669** [comment]
Server side: 

![2022-01-03_18h06_47](https://user-images.githubusercontent.com/18504086/147958961-f014e873-5c88-4391-984f-b41840ecf7da.png)

**Comment by tobystic** [comment]
@clem9669 did you get this resolved? How did you resolve this issue?

**Comment by tobystic** [comment]
@clem9669 I was able to get through this by removing port (since I was using socket )
